[package]
name = "loader"
version = "0.1.0"
edition = "2021"
repository= "https://github.com/bytemaker-io/log-parser"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.36.0"

