name: Rust Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Archive
        run: |
          if [ "${{ matrix.archive }}" = "zip" ]; then
            zip -r release.zip target/${{ matrix.target }}/release/*
          else
            tar -czvf release.tar.gz -C target/${{ matrix.target }}/release .
          fi
      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifact
          path: release.${{ matrix.archive }}
