name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build steps here

      - name: Archive code
        run: tar czvf archive.tar.gz *
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: archive
          path: archive.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: archive
          path: .

      - name: Set tag name
        id: prep
        run: |
          TAG_NAME=${GITHUB_REF#refs/*/}
          echo ::set-output name=TAG_NAME::${TAG_NAME}

      - name: Create Release
        run: |
          gh release create ${{ steps.prep.outputs.TAG_NAME }} \
            --title "Release ${{ steps.prep.outputs.TAG_NAME }}" \
            --notes "" \
            --draft=false \
            --prerelease=false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        run: |
          gh release upload ${{ steps.prep.outputs.TAG_NAME }} \
            ./archive.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
